services:
  _defaults:
    public: true

    # Grid
  openarticles.grid.definition.factory:
    public: true
    class: 'Ericc70\Openarticles\Grid\Definition\Factory\ArticleDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  openarticles.grid.query_builder:
    class: 'Ericc70\Openarticles\Grid\Query\ArticleQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'

  openarticles.grid.data.factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@openarticles.grid.query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'Articles'

  openarticles.grid.data.factory.decorator:
    class: 'Ericc70\Openarticles\Grid\Data\Factory\ArticleGridDataFactory'
    arguments:
      - '@openarticles.grid.data.factory'

  openarticles.grid.grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@openarticles.grid.definition.factory'
      - '@openarticles.grid.data.factory.decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
  
#Form
  openarticles.type.article:
    class: 'Ericc70\Openarticles\Form\Type\ArticleType'
    parent: 'form.type.translatable.aware'
    public: 'true'
    arguments:
      - '@openarticles.repository.article_repository'
    tags:
      - { name: form.type} 


  openarticles.form.identifiable.object.builder:
    class: 'PrestaShop\Prestashop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Ericc70\Openarticles\Form\Type\ArticleType'
      - '@openarticles.form.identifiable_object.data.provider'
  
  openarticles.form.identifiable_object.data.provider:
    class: 'Ericc70\Openarticles\Form\Provider\ArticleFormDataProvider'
    arguments: 
     - '@openarticles.repository.article_repository'

    ## FORM HANDLER

  openarticles.command.builder.article:
    class: 'Ericc70\Openarticles\CommandBuilder\ArticleCommandBuilder'
  
  openarticles.form.identifiable.object.data.handler:
    class: 'Ericc70\Openarticles\Form\DataHandler\ArticleFormDataHandler'
    arguments:
      - '@prestashop.core.command_bus'
      - '@openarticles.command.builder.article'

  openarticles.form.identifiable.object.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
     - '@openarticles.form.identifiable.object.data.handler'

  openarticles.command.handler.add_article:
    class: 'Ericc70\Openarticles\CommandHandler\AddArticleCommandHandler'
    arguments:
       - '@prestashop.core.admin.lang.repository'
       - '@doctrine.orm.default_entity_manager'
    tags:
     - { name: 'tactician.handler' , command: 'Ericc70\Openarticles\Command\AddArticleCommand'}

  openarticles.command.handler.edit_article:
    class: 'Ericc70\Openarticles\CommandHandler\EditArticleCommandHandler'
    arguments:
       - '@prestashop.core.admin.lang.repository'
       - '@openarticles.repository.article_repository'
       - '@doctrine.orm.default_entity_manager'
    tags:
     - { name: 'tactician.handler' , command: 'Ericc70\Openarticles\Command\EditArticleCommand'}

  # REPOSITORY

  openarticles.repository.article_repository:
    class: 'Ericc70\Openarticles\ArticleRepository'
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments: 
     - Ericc70\Openarticles\Entity\OpenArticles


    