oit_article_index:
  path: /
  methods: GET
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::indexAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

ec_article_create:
  path: /create
  methods: [GET, POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::createAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

ec_article_edit:
  path: /{articleId}/edit
  methods: [GET, POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::editAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles
  requirements:
    articleId: \d+

ec_article_delete:
  path: /{articleId}/delete
  methods: [POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::deleteAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles
  requirements:
    articleId: \d+
