oit_article_index:
  path: /
  methods: GET
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::indexAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

ec_article_search:
  path: /
  methods: POST
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::searchAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

ec_article_export:
  path: /export
  methods: Get
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::exportAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

ec_article_create:
  path: /create
  methods: [GET, POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::createAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

ec_article_edit:
  path: /{articleId}/edit
  methods: [GET, POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::editAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles
  requirements:
    articleId: \d+

ec_article_delete:
  path: /{articleId}/delete
  methods: [POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::deleteAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles
  requirements:
    articleId: \d+

ec_delete_bulk:
  path: /delete-bulk
  methods: [POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::deleteBulkAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

  

ec_bulk_status_enable:
  path: /enable-bulk
  methods: [POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::enableBulkAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

  
ec_bulk_status_disable:
  path: /disable-bulk
  methods: [POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::disableBulkAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

ec_update_positions:
  path: /update-positions
  methods: [GET]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::updatePositionsAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles

  

ec_toggle_status:
  path: /{articleId}/toggle-status
  methods: [POST]
  defaults: 
    _controller: Ericc70\Openarticles\Controller\AdminOpenArticles::toogleAction
    _disable_module_prefix: true
    _legacy_controller: AdminOpenArticles
    _legacy_link: AdminOpenArticles
  requirements:
    articleId: \d+

